version: '3.9'

services:
  client:
    build:
      context: ./client
    image: alexcodes100/2650-finalproject:client
    ports:
      - "4000:4000" # The internal client port
    environment:
      - REACT_APP_API_URL=http://3.85.135.37:3000/
    depends_on:
      - server
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
    image: alexcodes100/2650-finalproject:mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: ricardo
      MYSQL_PASSWORD: ricardo
    networks:
      - app-network

  server:
    build:
      context: ./server
    image: alexcodes100/2650-finalproject:server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SQL_HOST=mysql
      - SQL_USER=ricardo
      - SQL_PASSWORD=ricardo
      - SQL_DATABASE=db
      - CORS_ORIGIN=http://3.85.135.37:4000
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_HOST=http://3.85.135.37:4000
      - SERVER_HOST=http://3.85.135.37:3000/
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  redis:
    build:
      context: ./redis
    image: alexcodes100/2650-finalproject:redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
