version: '3.9'

services:
  client:
    build:
      context: ./client
    image: alexcodes100/2650-finalproject:client
    environment:
      - REACT_APP_API_URL=http://nginx/api/
    depends_on:
      - server
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
    image: alexcodes100/2650-finalproject:mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: ricardo
      MYSQL_PASSWORD: ricardo
    networks:
      - app-network

  server:
    build:
      context: ./server
    image: alexcodes100/2650-finalproject:server
    environment:
      - PORT=3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SQL_HOST=mysql
      - SQL_USER=ricardo
      - SQL_PASSWORD=ricardo
      - SQL_DATABASE=db
      - CORS_ORIGIN=http://nginx
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_HOST=http://nginx
      - SERVER_HOST=http://nginx/api/
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
