version: '3.9'

services:
  client:
    build:
      context: ./client
    image: alexcodes100/2650-finalproject:client
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_API_URL=http://nginx/api/
    depends_on:
      - server
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
    image: alexcodes100/2650-finalproject:mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: ricardo
      MYSQL_PASSWORD: ricardo
    networks:
      - app-network

  server:
    build:
      context: ./server
    image: alexcodes100/2650-finalproject:server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=cd1f3add13cb5fcaa12f3f8ba818c4b2d35d798920276dbe0483a6560f4cf31f57618a07d37e8676c597a425ba236c3137483fa16d6cf888e6c616e0898a85ac
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SQL_HOST=mysql
      - SQL_USER=ricardo
      - SQL_PASSWORD=ricardo
      - SQL_DATABASE=db
      - CORS_ORIGIN=http://nginx
      - JWT_SECRET=Mj8kPWxB9pLYXcYbl8bz8bt9ifZIEm+tTKXpvyYDPos=
      - CLIENT_HOST=http://nginx
      - SERVER_HOST=http://nginx/api/
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
