# Use the official MySQL image from the Docker Hub
FROM mysql:5.7

# Set the root password, and create a database
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mydatabase

# Expose the MySQL port
EXPOSE 3306
